### ISSUE TITLE
Mise en page

### ISSUE THREAD

**Issue by MaxBrtl** [TimSykdom/GCD-Sykdom#2]
Bonjour, 

faudrait revoir la mise en page y'en avait pas, heureusement on a Tanguy.

**Comment by MaxBrtl** [comment]
C'est bon on en a une nouvelle elle est très jolie, bien joué

**Comment by evaklein** [comment]
Bravo

**Comment by Sarahjanin** [comment]
Super

**Comment by Tanguydssgn** [comment]
pouce en l'air

**Comment by Paulsorinfo** [comment]
hello again
